### ISSUE TITLE
End coordinate of the last window of a sequence

### ISSUE THREAD

**Issue by muffato** [tolkit/fasta_windows#8]
Hi Max

I've found this bug when comparing the output to GDA's: the end coordinate is always the start coordinate plus the window size, but it should be capped by the chromosome length.
For instance, for _Vanessa atalanta_, it prints
```
LR990553.1      14397000        14398000
```
for the last entry of `LR990553.1`, but it should rather print this:
```
LR990553.1      14397000        14397436
```

**Comment by Euphrasiologist** [comment]
Hi Matthieu,

Thanks for raising this! I'll fix this as soon as I can.

M
